spring:
  application:
    name: eureka-server
server:
  port: 1028

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:  http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
  server:
    enableSelfPreservation: false






